### ISSUE TITLE
ASF Library Logic 

### ISSUE THREAD

**Issue by jeffeastman** [cqframework/payerextract#10]
When I run this in memory, it appears that the logic is trying to evaluate "effective" against a Procedure.  See [cqf-ruler Issue 24](https://github.com/DBCG/cqf-ruler/issues/24)

```
define "Numerator 2":
	"Initial Population"
	and
	exists (
		"Initial Positive Assessment for Unhealthy Alcohol Use" A
			with "Followup Screening" F such that F.effective.value 2 months or less after day of A.effective.value
	)

```

```
define "Followup Screening":
	([Procedure: "Alcohol Counseling and Treatment"] Proc
		where Proc.status.value = 'completed')
	union
	([Observation: "Alcohol Counseling and Treatment"] Obs
		where Obs.status.value in { 'final', 'amended' })
	union
	([Procedure: "Alcohol Screening"] Proc
		where Proc.status.value = 'completed')
	union
	([Observation: "Alcohol Screening"] Obs
		where Obs.status.value in { 'final', 'amended' })

```

**Comment by jeffeastman** [comment]
I closed the cqf-ruler issue because the measure no longer fails on that server, but it still fails in my in-memory ResourceProvider using all of the same jars & Libraries. None of the above logic appears to have changed, so I'm at a loss to explain why it works on the server.

**Comment by jeffeastman** [comment]
I think I see where the fix went into _JpaDataProvider_. Changing **effective.value** to the more generic **date** search parameter works around the inconsistencies in the FHIR resources and lets the above CQL do its job.

Could **F.effective.value** be changed to **F.date** in the CQL?

```
    public String convertDatePath(String path) {
        if (path.contains("effective")) {
            return "date";
        }

        return path;
    }

```

**Comment by c-schuler** [comment]
No, F.date will fail during translation since Procedure does have a date search parameter, but it doesn't have a date property.

**Comment by jeffeastman** [comment]
Ah, ok. The rewrite in cqf-ruler works because its rewriting to a search parameter. I don't have that luxury in my in-memory DataProvider because, like the translator, it doesn't have a date property. I'll have to code a different workaround.

The CQL is still wrong though, correct?

**Comment by c-schuler** [comment]
Yes, the CQL needs to be reworked. @duncand would you please address the errors in the ASF library?

**Comment by duncand** [comment]
Please see commit https://github.com/cqframework/hedis-ig/commit/44079f0333904cfaa0b4a9544ef1ed151b451b4d where I refactored "Followup Screening" to account for the field name differences.  I expect no one calls "Followup Screening" directly from outside the measure, or otherwise this change will break that.

**Comment by jeffeastman** [comment]
That looks like it will resolve the issue. How do I get the library updated? I tried building the project but there are so many files I'm not sure which are the ones to use. The ones in resources or the ones in pages or the ones in temp? Are they even consistent? The file dates don't show that.

**Comment by c-schuler** [comment]
@duncand : the performed property for Hedis Procedures have been constrained to be of type Period. Therefore, Procedure.performed.value will give an error as Period has no value property.

@jeffeastman : I will update the FHIR Library resource in this repo once the CQL is fixed.

**Comment by jeffeastman** [comment]
Curious how the CQL->Library generation is done? Do you have a link or a snippet?

**Comment by duncand** [comment]
New commit https://github.com/cqframework/hedis-ig/commit/a22ea89126f32eb828bc2a4897e717e5cfc8326e should handle Procedures using Periods.

**Comment by c-schuler** [comment]
Thanks Darren.
The way we generate the Libraries from CQL consists of translating the CQL to elm, then encoding the ELM as a base64 string, then attaching that as the content. We have automated this process (along with determining the dataRequirements), but it isn't publicly available yet. I'd be happy to share the code with you if you're interested.

**Comment by c-schuler** [comment]
The ASF Library resource has been updated with the updated logic.

**Comment by jeffeastman** [comment]
Sure, I'd love to see how that's done.

**Comment by jeffeastman** [comment]
Latest library updates did the trick. My in-memory evaluator now runs:

```
Measure = Measure/measure-asf
	denominator = 91
	initial-population = 76
	numerator = 30

```
