### ISSUE TITLE
Interval type missing in MRP library definition

### ISSUE THREAD

**Issue by barhodes** [cqframework/payerextract#16]
The definition "Encounters without 30 Day Readmission" in the mrp logic library gives an error stating an interval type is expected at start of E2.period

**Comment by brynrhodes** [comment]
This is caused by a known issue in the 1.3.10 release of the translator: https://github.com/cqframework/clinical_quality_language/issues/397
It is addressed in the 1.3.14 release: https://github.com/cqframework/clinical_quality_language/releases/tag/v1.3.14

**Comment by brynrhodes** [comment]
Fixed per the 1.3.15 release of the translator.
