### ISSUE TITLE
Value set definitions

### ISSUE THREAD

**Issue by dwwinters** [cqframework/payerextract#24]
I'm trying to find out more information about some of the value sets referenced in the Unhealthy Alcohol Use Screening and Follow-up library.  For instance, `2.16.840.1.113883.3.464.1004.1437` doesn't seem to be included with the IG as a FHIR ValueSet resource, nor can it be found on PHIN VADS or VSAC.  Just wondering if this and other value sets will be published at some point in the future.  Thank you.

**Comment by c-schuler** [comment]
The HEDIS ValueSet resources are proprietary IP, which we are not allowed to make publicly available.

**Comment by dwwinters** [comment]
Thanks for the response @c-schuler .
